In [2]:
import pandas as pd
from curated_set_services import CuratedSet

In [2]:
df = pd.read_csv("human_histones.csv",engine='python').fillna('')
df.shape, df.columns

((107, 19),
 Index(['accession', 'type', 'variant_group', 'variant',
        'Clustered (canonical) isoform', 'ncbi_gene_id', 'hgnc_gene_name',
        'Ensembl gene ID', 'Transcript stable ID', 'RefSeq mRNA ID',
        'RefSeq peptide ID', 'Protein length', 'taxonomy_id', 'organism',
        'phylum', 'class', 'taxonomy_group', 'info', 'references'],
       dtype='object'))

In [12]:
df_to_add = df[['accession', 'type', 'variant_group', 'variant', 'ncbi_gene_id', 'hgnc_gene_name',
                'taxonomy_id', 'organism', 'phylum', 'class', 'taxonomy_group', 'info', 'references']]
df_to_add['sequence'] = ['']*df_to_add.shape[0]

<ipython-input-12-c3db02a57cb8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_to_add['sequence'] = ['']*df_to_add.shape[0]

In [13]:
df_to_add.head()

,accession,type,variant_group,variant,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,references,sequence
0,NP_005309.1,H1,H1.0,H1.0_(Homo_sapiens),3005,H1-0,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
1,NP_005316.1,H1,H1.1,H1.1_(Homo_sapiens),3024,H1-1,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
2,NP_005310.1,H1,H1.2,H1.2_(Homo_sapiens),3006,H1-2,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
3,NP_005311.1,H1,H1.3,H1.3_(Homo_sapiens),3007,H1-3,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
4,NP_005312.1,H1,H1.4,H1.4_(Homo_sapiens),3008,H1-4,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,

In [5]:
#Load data from histones.csv
curated_set = CuratedSet()
cs=curated_set

In [6]:
cs.data.head(3)

,accession,type,variant_group,variant,doublet,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,references,sequence
NP_505463.1,NP_505463.1,H2A,cH2A,cH2A_(Animals),,17562014,,,6239,Caenorhabditis elegans,Nematoda,Chromadorea,,,26989147 22650316(?),MSGRGKGGKAKTGGKAKSRSSRAGLQFPVGRLHRILRKGNYAQRVG...
EEC09557.1,EEC09557.1,H2A,cH2A,cH2A_(Animals),,215500063,,,6945,Ixodes scapularis,Arthropoda,Arachnida,,,26989147 22650316(?),MSGRGKGGKVKGKSKTRSSRAGLQFPVGRIHRLLRKGNYAERVGAG...
NP_724343.1,NP_724343.1,H2A,cH2A,cH2A_(Animals),,24585673,,,7227,Drosophila melanogaster,Arthropoda,Insecta,,,26989147 22650316(?),MSGRGKGGKVKGKAKSRSNRAGLQFPVGRIHRLLRKGNYAERVGAG...

In [7]:
cs.data[cs.data['variant'].str.contains('__\?\?\?')]

,accession,type,variant_group,variant,doublet,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,references,sequence
XP_637656.1,XP_637656.1,H2A,generic_H2A,generic_H2A__???,,66807867,,,352472,Dictyostelium discoideum AX4,Evosea,Eumycetozoa,,classify __???,,MTESETTSKKVNKRVKPVPKSTKAGLIFPVGRIHRMLKNKVPLKRV...
NP_958924.1,NP_958924.1,H2A,H2A.Z,H2A.Z.2_(Homo_sapiens)__???,,,94239.0,H2AZ2,9606,Homo sapiens,Chordata,Mammalia,Mammalia,remove splice isoform 3 >__???,22467210 33771851 33073403,
NP_958925.1,NP_958925.1,H2A,H2A.Z,H2A.Z.2_(Homo_sapiens)__???,,,94239.0,H2AZ2,9606,Homo sapiens,Chordata,Mammalia,Mammalia,remove splice isoform 3 >__???,22467210 33771851 33073403,
NP_613075.1,NP_613075.1,H2A,macroH2A,macroH2A.1_(Homo_sapiens)__???,,,9555.0,MACROH2A1,9606,Homo sapiens,Chordata,Mammalia,Mammalia,see 10.1038/nsmb956,9138085 20543561 31015383,
NP_613258.2,NP_613258.2,H2A,macroH2A,macroH2A.1_(Homo_sapiens)__???,,,9555.0,MACROH2A1,9606,Homo sapiens,Chordata,Mammalia,Mammalia,see 10.1038/nsmb956,9138085 20543561 31015383,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NP_005311.1,NP_005311.1,H1,,H1.3_(Homo_sapiens)__???,,,3007.0,H1-3,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
NP_005314.2,NP_005314.2,H1,,H1.6_(Homo_sapiens)__???,,,3010.0,H1-6,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
NP_005309.1,NP_005309.1,H1,,H1.0_(Homo_sapiens)__???,,,3005.0,H1-0,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
NP_861453.1,NP_861453.1,H1,,H1.7_(Homo_sapiens)__???,,,341567.0,H1-7,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,
NP_005312.1,NP_005312.1,H1,,H1.4_(Homo_sapiens)__???,,,3008.0,H1-4,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,26689747,

In [8]:
cs.data.shape

(447, 16)

In [9]:
# Remove human histones from the dataset
print("Dropping %d records"%len(cs.data[cs.data.taxonomy_id == "9606"]))
cs.data = cs.data.drop(cs.data[cs.data.taxonomy_id == "9606"].index)
cs.data.head(3)

Dropping 105 records

,accession,type,variant_group,variant,doublet,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,references,sequence
NP_505463.1,NP_505463.1,H2A,cH2A,cH2A_(Animals),,17562014,,,6239,Caenorhabditis elegans,Nematoda,Chromadorea,,,26989147 22650316(?),MSGRGKGGKAKTGGKAKSRSSRAGLQFPVGRLHRILRKGNYAQRVG...
EEC09557.1,EEC09557.1,H2A,cH2A,cH2A_(Animals),,215500063,,,6945,Ixodes scapularis,Arthropoda,Arachnida,,,26989147 22650316(?),MSGRGKGGKVKGKSKTRSSRAGLQFPVGRIHRLLRKGNYAERVGAG...
NP_724343.1,NP_724343.1,H2A,cH2A,cH2A_(Animals),,24585673,,,7227,Drosophila melanogaster,Arthropoda,Insecta,,,26989147 22650316(?),MSGRGKGGKVKGKAKSRSNRAGLQFPVGRIHRLLRKGNYAERVGAG...

In [14]:
cs.data.shape

(342, 16)

In [15]:
cs.data=cs.data.append(df_to_add).fillna('')
cs.data.tail(3)

,accession,type,variant_group,variant,doublet,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,references,sequence
104,NP_003539.1,H4,cH4,cH4_(Homo_sapiens),,,8370,H4C14,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,12408966,
105,NP_001029249.1,H4,cH4,cH4_(Homo_sapiens),,,554313,H4C15,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,12408966,
106,NP_778224.1,H4,cH4,cH4_(Homo_sapiens),,,121504,H4C16,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,12408966,

In [16]:
# Identifying duplicated accessions
list(cs.has_duplicates())

[]

In [18]:
cs.data.shape

(449, 16)

In [19]:
len(set(cs.data['accession']))

449

In [20]:
# check with NCBI if accesssions have new versions and update them. E.g. NP_12345.1 has now NP_12345.2.
# from Bio import Entrez
# Entrez.email = 'histoneDB@intbio.org'
# cs.update_accession_version()
cs.data=cs.data.set_index(cs.data.accession.values)

In [21]:
# Identifying duplicated accessions
list(cs.has_duplicates())

[]

In [22]:
cs.data.tail(3)

,accession,type,variant_group,variant,doublet,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,references,sequence
NP_003539.1,NP_003539.1,H4,cH4,cH4_(Homo_sapiens),,,8370,H4C14,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,12408966,
NP_001029249.1,NP_001029249.1,H4,cH4,cH4_(Homo_sapiens),,,554313,H4C15,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,12408966,
NP_778224.1,NP_778224.1,H4,cH4,cH4_(Homo_sapiens),,,121504,H4C16,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,12408966,

In [24]:
data_old = cs.read_data("histones.csv")
data_old.loc[set(cs.data.index).intersection(set(data_old.index))]

,accession,type,variant_group,variant,doublet,gi,ncbi_gene_id,hgnc_gene_name,taxonomy_id,organism,phylum,class,taxonomy_group,info,references,sequence
ACO10502.1,ACO10502.1,H1,H1.10,H1.10,,225709312,,,217165,Caligus rogercresseyi,Arthropoda,Hexanauplia,,,,MVKSEVEVTINAEEAPVASSLKPAKKKKNKKKKNKPGKYSVLVLDA...
EHB05905.1,EHB05905.1,H2A,short_H2A,H2A.B,,351702986,,,10181,Heterocephalus glaber,Chordata,Mammalia,,,26989147 22650316(?),MPRQALALTNERPPQGRAEPIFSVSQVERALCDGRYAQRLSCSASV...
DAA13058.1,DAA13058.1,H2B,H2B.W,H2B.W,,296470943,,,9913,Bos taurus,Chordata,Mammalia,,,,MGIGGSILSETSSDSYEEDVITKETGISEIEPSEKEMAKVETSKPD...
NP_059141.1,NP_059141.1,H2B,,clustered H2B(?)_(Homo_sapiens)__???,,,54145.0,H2BC12L,9606,Homo sapiens,Chordata,Mammalia,Mammalia,,?,
NP_032223.2,NP_032223.2,H1,H1.0,H1.0,,31560697,,,10090,Mus musculus,Chordata,Mammalia,,,,MTENSTSAPAAKPKRAKASKKSTDHPKYSDMIVAAIQAEKNRAGSS...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NP_001044904.1,NP_001044904.1,H3,cH3,cH3,,115441249,,,39947,Oryza sativa Japonica Group,Streptophyta,Magnoliopsida,,,,MARTKQTARKSTGGKAPRKQLATKAARKSAPATGGVKKPHRFRPGT...
XP_001119899.1,XP_001119899.1,H2A,cH2A,cH2A_(Animals),,110764935,,,7460,Apis mellifera,Arthropoda,Insecta,,,26989147 22650316(?),MSGRGKGGKAKAKAKSRSNRAGLQFPVGRIHRLLRKGNYAERVGAG...
Q27750.3,Q27750.3,H2B,sperm_H2B,sperm_H2B__???,,108860775,,,7660,Psammechinus miliaris,Echinodermata,Echinoidea,,,,MPKSPSKSSPRKGSPRKGSPRKGSPKRGGKGAKRAGKGGRRNVVKR...
NP_036544.1,NP_036544.1,H2A,H2A.Z,H2A.Z.2.s1_(Homo_sapiens),,,94239.0,H2AZ2,9606,Homo sapiens,Chordata,Mammalia,Mammalia,remove splice isoform 3 >__???,22467210 33771851 33073403,
XP_002977792.1,XP_002977792.1,H3,cH3,cH3,,302792052,,,88036,Selaginella moellendorffii,Streptophyta,Lycopodiopsida,,,,MARTKQTARKSTGGKAPRKQLATKAARKSAPTTGGVKKPHRYRPGT...

In [23]:
data_old = cs.read_data("histones.csv")
data_old.loc[cs.data.index]

KeyError: "['NG_066059.1', 'NM_001395555.1'] not in index"

In [25]:
cs.save()

variant_group  self
               other                                 cH2B(?)
variant        self     clustered H2B(?)_(Homo_sapiens)__???
               other             cH2B(?)_(Homo_sapiens)__???
taxonomy_id    self                                     9606
               other                                    9606
info           self                                      NaN
               other                                     NaN
Name: NP_059141.1, dtype: object
variant_group  self                     NaN
               other                    NaN
variant        self                     NaN
               other                    NaN
taxonomy_id    self                    9606
               other                   9606
info           self     see 10.1038/nsmb956
               other
Name: NP_061119.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_003510.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_778225.1, dtype: object
variant_group  self
               other    cenH3
variant        self       NaN
               other      NaN
taxonomy_id    self      9606
               other     9606
info           self       NaN
               other      NaN
Name: NP_001035891.1, dtype: object
variant_group  self
               other    H1.8
variant        self      NaN
               other     NaN
taxonomy_id    self     9606
               other    9606
info           self      NaN
               other     NaN
Name: NP_001295191.1, dtype: object
variant_group  self                   NaN
               other                  NaN
variant        self                   NaN
               other                  NaN
taxonomy_id    self                  9606
               other                 9606
info           self     endoded by H2AC17
               other
Name: NP_003505.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003537.1, dtype: object
variant_group  self
               other                                 cH3.1
variant        self     clustered H3.1_(Homo_sapiens)__???
               other                  cH3.1_(Homo_sapiens)
taxonomy_id    self                                   9606
               other                                  9606
info           self                                    NaN
               other                                   NaN
Name: NP_003528.1, dtype: object
variant_group  self                  NaN
               other                 NaN
variant        self                  NaN
               other                 NaN
taxonomy_id    self                 9606
               other                9606
info           self     endoded by H2AC6
               other
Name: NP_003503.1, dtype: object
variant_group  self
               other    H3.Y.1
variant        self        NaN
               other       NaN
taxonomy_id    self       9606
               other      9606
info           self        NaN
               other       NaN
Name: NP_001342187.1, dtype: object
variant_group  self
               other    H2B.W
variant        self       NaN
               other      NaN
taxonomy_id    self      9606
               other     9606
info           self       NaN
               other      NaN
Name: NP_001002916.4, dtype: object
variant_group  self
               other    H2B.N
variant        self       NaN
               other      NaN
taxonomy_id    self      9606
               other     9606
info           self       NaN
               other      NaN
Name: NP_001388269.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_003509.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003486.1, dtype: object
variant_group  self                   NaN
               other                  NaN
variant        self                   NaN
               other                  NaN
taxonomy_id    self                  9606
               other                 9606
info           self     endoded by H2AC18
               other
Name: NP_003507.1, dtype: object
variant_group  self                                NaN
               other                               NaN
variant        self                                NaN
               other                               NaN
taxonomy_id    self                               9606
               other                              9606
info           self     remove splice isoform 3 >__???
               other
Name: NP_958924.1, dtype: object
variant_group  self
               other                                 cH3.2
variant        self     clustered H3.2_(Homo_sapiens)__???
               other                  cH3.2_(Homo_sapiens)
taxonomy_id    self                                   9606
               other                                  9606
info           self                                    NaN
               other                                   NaN
Name: NP_001116847.1, dtype: object
variant_group  self                  NaN
               other                 NaN
variant        self                  NaN
               other                 NaN
taxonomy_id    self                 9606
               other                9606
info           self     endoded by H2AC8
               other
Name: NP_066390.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_003519.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003539.1, dtype: object
variant_group  self
               other                                 cH3.1
variant        self     clustered H3.1_(Homo_sapiens)__???
               other                  cH3.1_(Homo_sapiens)
taxonomy_id    self                                   9606
               other                                  9606
info           self                                    NaN
               other                                   NaN
Name: NP_003520.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003533.1, dtype: object
variant_group  self                                NaN
               other                               NaN
variant        self                                NaN
               other                               NaN
taxonomy_id    self                               9606
               other                              9606
info           self     remove splice isoform 3 >__???
               other
Name: NP_958844.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_003515.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003532.1, dtype: object
variant_group  self
               other                                 cH3.1
variant        self     clustered H3.1_(Homo_sapiens)__???
               other                  cH3.1_(Homo_sapiens)
taxonomy_id    self                                   9606
               other                                  9606
info           self                                    NaN
               other                                   NaN
Name: NP_066298.1, dtype: object
variant_group  self
               other    H1.8
variant        self      NaN
               other     NaN
taxonomy_id    self     9606
               other    9606
info           self      NaN
               other     NaN
Name: NP_722575.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003535.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_001299582.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_003517.2, dtype: object
variant_group  self
               other    cenH3
variant        self       NaN
               other      NaN
taxonomy_id    self      9606
               other     9606
info           self       NaN
               other      NaN
Name: NP_001800.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_003516.1, dtype: object
variant_group  self
               other                                 cH3.1
variant        self     clustered H3.1_(Homo_sapiens)__???
               other                  cH3.1_(Homo_sapiens)
taxonomy_id    self                                   9606
               other                                  9606
info           self                                    NaN
               other                                   NaN
Name: NP_003522.1, dtype: object
variant_group  self                   NaN
               other                  NaN
variant        self                   NaN
               other                  NaN
taxonomy_id    self                  9606
               other                 9606
info           self     endoded by H2AC11
               other
Name: NP_066408.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003530.1, dtype: object
variant_group  self                   NaN
               other                  NaN
variant        self                   NaN
               other                  NaN
taxonomy_id    self                  9606
               other                 9606
info           self     endoded by H2AC19
               other
Name: NP_001035807.1, dtype: object
variant_group  self
               other                                 cH4
variant        self     clustered H4_(Homo_sapiens)__???
               other             cH4_(Homo_sapiens)__???
taxonomy_id    self                                 9606
               other                                9606
info           self                                  NaN
               other                                 NaN
Name: NP_003536.1, dtype: object
variant_group  self      NaN
               other     NaN
variant        self      NaN
               other     NaN
taxonomy_id    self     9606
               other    9606
info           self      NaN
               other     NaN
Name: NP_808760.1, dtype: object
variant_group  self                                NaN
               other                               NaN
variant        self                                NaN
               other                               NaN
taxonomy_id    self                               9606
               other                              9606
info           self     remove splice isoform 3 >__???
               other
Name: NP_958925.1, dtype: object
variant_group  self
               other                                 cH3.2
variant        self     clustered H3.2_(Homo_sapiens)__???
               other                  cH3.2_(Homo_sapiens)
taxonomy_id    self                                   9606
               other                                  9606
info           self                                    NaN
               other                                   NaN
Name: NP_066403.2, dtype: object
variant_group  self
               other    H2B.K
variant        self       NaN
               other      NaN
taxonomy_id    self      9606
               other     9606
info           self       NaN
               other      NaN
Name: NP_001356054.2, dtype: object
variant_group  self                     NaN
               other                    NaN
variant        self                     NaN
               other                    NaN
taxonomy_id    self                    9606
               other                   9606
info           self     see 10.1038/nsmb956
               other
Name: NP_613075.1, dtype: object
variant_group  self
               other    H1.5
variant        self      NaN
               other     NaN
taxonomy_id    self     9606
               other    9606
info           self      NaN
               other     NaN
Name: NP_005313.1, dtype: object
variant_group  self                   NaN
               other                  NaN
variant        self                   NaN
               other                  NaN
taxonomy_id    self                  9606
               other                 9606
info           self     endoded by H2AC15
               other
Name: NP_003501.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_066406.1, dtype: object
variant_group  self                  NaN
               other                 NaN
variant        self                  NaN
               other                 NaN
taxonomy_id    self                 9606
               other                9606
info           self     endoded by H2AC7
               other
Name: NP_066409.1, dtype: object
variant_group  self
               other                                 cH3.2
variant        self     clustered H3.2_(Homo_sapiens)__???
               other                  cH3.2_(Homo_sapiens)
taxonomy_id    self                                   9606
               other                                  9606
info           self                                    NaN
               other                                   NaN
Name: NP_001005464.1, dtype: object
variant_group  self                   NaN
               other                  NaN
variant        self                   NaN
               other                  NaN
taxonomy_id    self                  9606
               other                 9606
info           self     endoded by H2AC20
               other
Name: NP_003508.1, dtype: object
variant_group  self
               other                                 cH2B
variant        self     clustered H2B_(Homo_sapiens)__???
               other                  cH2B_(Homo_sapiens)
taxonomy_id    self                                  9606
               other                                 9606
info           self                                   NaN
               other                                  NaN
Name: NP_003511.1, dtype: object
variant_group  self      NaN
               other     NaN
variant        self      NaN
               other     NaN
taxonomy_id    self     9606
               other    9606
info           self      NaN
               other     NaN